### ISSUE TITLE
Ay kai hamo jaam check kori sahi ko ... tafseelat commenta sheni

### ISSUE THREAD

**Issue by explorest** [sumirabanu/testing#2]
jasdgasgasa
sh
a
dh

fh
asd
h
a
fha
df
ha
fh
a
dfg
afgasfg
as
ga
s
gda
sg
asd
g
adsg
asg
sd
gas
g
sda
gasd
gf

**Comment by sumirabanu** [comment]
ava hamo change kore maslo hal atm
